; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = genericSTM32F103C8
board_build.stm32cube.custom_config_header = yes
framework = stm32cube
lib_deps = 
	https://github.com/starfactorypixel/PixelConstantsLibrary
	https://github.com/starfactorypixel/Library_CUtils
	https://github.com/starfactorypixel/PixelCANLibrary
	https://github.com/starfactorypixel/Library_PixelLed
	https://github.com/starfactorypixel/PixelLoggerLibrary
	https://github.com/starfactorypixel/Library_DrakePin
	https://github.com/starfactorypixel/Library_PixelSPI
	https://github.com/starfactorypixel/Library_PixelAnalogMux
	https://github.com/starfactorypixel/Library_PixelOneWire
debug_tool = stlink
monitor_speed = 500000
monitor_port = COM3
build_flags = 
	-D ENV_CAN_FIRST_ID=0x0100

[env:Debug]
build_type = debug
build_unflags = 
build_flags = 
	${env.build_flags}
	-D DEBUG

[env:Release]
build_type = release
build_unflags = 
build_flags = 
	${env.build_flags}
